// Code generated by MockGen. DO NOT EDIT.
// Source: graphite_writer.go
//
// Generated by this command:
//
//	mockgen -source graphite_writer.go
//

// Package mock_graphite_log is a generated GoMock package.
package mock_graphite_log

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGraphiteInterface is a mock of GraphiteInterface interface.
type MockGraphiteInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGraphiteInterfaceMockRecorder
}

// MockGraphiteInterfaceMockRecorder is the mock recorder for MockGraphiteInterface.
type MockGraphiteInterfaceMockRecorder struct {
	mock *MockGraphiteInterface
}

// NewMockGraphiteInterface creates a new mock instance.
func NewMockGraphiteInterface(ctrl *gomock.Controller) *MockGraphiteInterface {
	mock := &MockGraphiteInterface{ctrl: ctrl}
	mock.recorder = &MockGraphiteInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphiteInterface) EXPECT() *MockGraphiteInterfaceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockGraphiteInterface) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockGraphiteInterfaceMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockGraphiteInterface)(nil).Connect))
}

// Reconnect mocks base method.
func (m *MockGraphiteInterface) Reconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconnect indicates an expected call of Reconnect.
func (mr *MockGraphiteInterfaceMockRecorder) Reconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconnect", reflect.TypeOf((*MockGraphiteInterface)(nil).Reconnect))
}

// Send mocks base method.
func (m *MockGraphiteInterface) Send(path, value string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", path, value)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockGraphiteInterfaceMockRecorder) Send(path, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGraphiteInterface)(nil).Send), path, value)
}
