// Code generated by MockGen. DO NOT EDIT.
// Source: graphite_writer.go
//
// Generated by this command:
//
//	mockgen -source=graphite_writer.go -destination mock/graphite_write_mock.go
//

// Package mock_graphite_log is a generated GoMock package.
package mock_graphite_log

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGraphiteInterface is a mock of GraphiteInterface interface.
type MockGraphiteInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGraphiteInterfaceMockRecorder
}

// MockGraphiteInterfaceMockRecorder is the mock recorder for MockGraphiteInterface.
type MockGraphiteInterfaceMockRecorder struct {
	mock *MockGraphiteInterface
}

// NewMockGraphiteInterface creates a new mock instance.
func NewMockGraphiteInterface(ctrl *gomock.Controller) *MockGraphiteInterface {
	mock := &MockGraphiteInterface{ctrl: ctrl}
	mock.recorder = &MockGraphiteInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphiteInterface) EXPECT() *MockGraphiteInterfaceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockGraphiteInterface) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockGraphiteInterfaceMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockGraphiteInterface)(nil).Connect))
}

// Disconnect mocks base method.
func (m *MockGraphiteInterface) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockGraphiteInterfaceMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockGraphiteInterface)(nil).Disconnect))
}

// SimpleSend mocks base method.
func (m *MockGraphiteInterface) SimpleSend(path, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimpleSend", path, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SimpleSend indicates an expected call of SimpleSend.
func (mr *MockGraphiteInterfaceMockRecorder) SimpleSend(path, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimpleSend", reflect.TypeOf((*MockGraphiteInterface)(nil).SimpleSend), path, value)
}
